Skip SPI re-init if clock frequency doesn't change
earlephilhower/arduino-pico pull request #1934
Opened 2024-01-11 17:38 UTC by Nerradia

Hello,

In link with #392, I have two SPI devices that use the same clock frequency but not the same clock polarity. From what I've seen, re-initing the whole SPI is slow and unecessary when clock is the same.

I haven't done much testing but it works in my case.

2024-01-11 21:41 UTC, earlephilhower requested changes

2024-01-11 21:41 UTC, earlephilhower commented on libraries/SPI/src/SPI.cpp
> +          spi_init(_spi, _spis.getClockFreq());
This is backwards, actually.  `settings` is the new value (you've moved the copy `_spis = settings` after this block) so you want `spi_init(_spi, settings.getClockFreq());` I believe.

2024-01-21 12:09 UTC, Nerradia commented
Sorry I've been wuite busy last week. I have fixed the code as you requested. I guess I can't update this PR if it is closed ?

2024-01-21 13:25 UTC, earlephilhower commented
Try it now, please.

2024-01-27 10:08 UTC, Nerradia commented
Alright, I think the formatting is good now.
Sorry for struggling a bit, that's my first PR !

2024-01-28 18:15 UTC, earlephilhower approved these changes
Thanks for getting this cleaned up!

2024-01-28 18:27 UTC, merged