Add Elecrow CrowPanel RP2040 DVI board
earlephilhower/arduino-pico pull request #2269
Opened 2024-07-16 06:55 UTC by qq71680264

I've generated boards.txt via makeboards.py in the latest code, added the required files, and tested it to run silky smooth on an Elecrow CrowPanel RP2040 DVI board. This is the first time I've been involved in submitting code, so if I haven't gotten it right somewhere, please remind me and I'll do my best to get it right.

2024-07-16 17:39 UTC, earlephilhower requested changes
The CI run shows a difference in multiple files from what you've checked in.  You should never edit anything other than makeboards.py and readme.md to add a board.  `Boards.txt` and the JSON files are machine generated.

2024-07-16 17:39 UTC, earlephilhower commented on tools/makeboards.py
> +# Elecrow
Alphabetically, this should be placed before ElectronicCat.

2024-07-17 01:21 UTC, qq71680264 commented
Oh, i read the "contrib.rst", and maybe i know how to do it now. The only files that need to be added manually are the ones in the “variants” folder, the rest are generated by makeboards.py, is that correct?

2024-07-17 01:24 UTC, earlephilhower commented
> Oh, i read the "contrib.rst", and maybe i know how to do it now. The only files that need to be added manually are the ones in the “variants” folder, the rest are generated by makeboards.py, is that correct?

Yes, that's pretty much it.  The `makeboards.py` script updates the package JSON, the P.IO JSONs, and boards.txt.  None of those outputs should be edited.

2024-07-17 02:35 UTC, closed without merging