Overclock to 153.6 MHz (instead of 147.6 MHz) for I²S 48 kHz sample rate
earlephilhower/arduino-pico pull request #2708
Opened 2024-12-20 12:39 UTC by magy00

Increasing `clk_sys` by another 6 MHz would allow for exact 96 kHz and 192 kHz sampling rates (apart from the ±30 ppm of Pico's 12 MHz crystal itself).

2024-12-20 15:22 UTC, earlephilhower requested changes

2024-12-20 15:22 UTC, earlephilhower commented on tools/makeboards.py
> +    for f in [ defmhz, 50, 100, 120, 125, 128, 133, 150, 153.6, 175, 200, 225, 240, 250, 275, 300]:
This requires re-running the script and checking in the updated boards.txt or CI will fail.

2024-12-20 15:25 UTC, earlephilhower commented
> Should `I2S::setSysClk()` return `true` if `clk_sys` was (successfully) changed, or should it return `false` only if any change attempt was unsuccessful (or should it `panic()` instead)?

In theory if there's a return code I'd not panic and return true if the machine state on output of the function is what I requested (even if it was already good).  So your returning of the set_sys_clk is fine.

2024-12-21 12:25 UTC, earlephilhower approved these changes
Thanks!

2024-12-21 15:36 UTC, merged

2024-12-31 22:22 UTC, frohro commented
This is a really nice improvement!  Thanks!