Use PIN_I2S_ defines if they exist in board pin definition.
earlephilhower/arduino-pico pull request #991
Opened 2022-11-20 19:49 UTC by DatanoiseTV

Make the usage more user friendly and use PIN_I2S_ pin definitions if they are defined in the board pins_arduino.h.

For example: https://github.com/DatanoiseTV/arduino-pico/blob/master/variants/datanoisetv_picoadk/pins_arduino.h#L43

2022-11-21 16:47 UTC, earlephilhower requested changes
I like your idea, but this really isn't the way to do it with the way the class is architected now.

These defaults should be se set in the `I2S::I2S` constructor and not the `::begin`.  See https://github.com/earlephilhower/arduino-pico/blob/master/libraries/I2S/src/I2S.cpp#L26-L39

2022-11-21 17:02 UTC, DatanoiseTV commented
@earlephilhower Would this work for you?
```cpp
I2S::I2S(PinMode direction) {
    _running = false;
    _bps = 16;
    _writtenHalf = false;
    _isOutput = direction == OUTPUT;
#ifdef PIN_I2S_BCLK
    _pinBCLK = PIN_I2S_BCLK;
#else
    _pinBCLK = 26;
#endif

#ifdef PIN_I2S_DOUT
    if (_isOutput == OUTPUT) {
        _pinDOUT = PIN_I2S_DOUT;
    }
#endif

#ifdef PIN_I2S_DIN
    if (_isOutput == INPUT) {
        _pinDOUT = PIN_I2S_DIN;
    }
#endif
    _freq = 48000;
    _arb = nullptr;
    _cb = nullptr;
    _buffers = 8;
    _bufferWords = 16;
    _silenceSample = 0;
}
```

2022-11-21 17:36 UTC, earlephilhower commented
That looks good, yes!

2022-11-21 17:38 UTC, DatanoiseTV commented
@earlephilhower The weird thing is just the _pinDOUT confusion. It would be good to support both INPUT and OUTPUT and combined mode for I2S audio codec. Do you have an idea how to solve it?

2022-11-21 18:08 UTC, earlephilhower commented
The way the state machine works it's not possible to do both shift directions in the same PIO SM.  So you need 2 separate state machines if you want bidirectional.  (They can, of course, be running completely different bit widths, frequencies, etc.)

2022-11-23 01:15 UTC, earlephilhower commented
@DatanoiseTV can you update the PR with what we discussed above?  That way it can be included in the next release this Friday or Saturday...

2022-11-23 01:19 UTC, DatanoiseTV commented
> @DatanoiseTV can you update the PR with what we discussed above? That way it can be included in the next release this Friday or Saturday...

Sorry, done just now.

2022-11-23 01:20 UTC, earlephilhower requested changes

2022-11-23 01:20 UTC, earlephilhower commented on libraries/I2S/src/I2S.cpp
> +    if (_isOutput == OUTPUT) {
I think you mean "`if (_isOutput)` since this is a boolean...

2022-11-23 01:20 UTC, earlephilhower commented on libraries/I2S/src/I2S.cpp
> +    if (_isOutput == INPUT) {
Same as above...`if (!_isOutput)`...

2022-11-23 01:21 UTC, earlephilhower commented
Thx, but I think there's a couple minor things as noted.  OTW looks good!

2022-11-23 01:23 UTC, earlephilhower approved these changes
Thanks!

2022-11-23 01:42 UTC, merged